(function(b){b.fn.message=function(a){Array.prototype.forEach||(Array.prototype.forEach=function(a,c){var d=this.length;if("function"!=typeof a)throw new TypeError;for(var b=0;b<d;b++)b in this&&a.call(c,this[b],b,this)});if("hide"==a)b(this).find(".message_error_container").hide("slide",{direction:"up"},500);else{var j={},n=b(this).is("html")?b("body").children(".container").width():b(this).width();if("string"===typeof a)var h=a;else"undefined"===typeof a.error_content?j="Message content can not be empty.":
h=a.error_content;if("undefined"===typeof a.error_type)var e="error";else"string"===typeof a.error_type?"error"==a.error_type||"info"==a.error_type||"warning"==a.error_type||"success"==a.error_type?e=a.error_type:j="Invalid message type. See Documentation.":e=a.error_type;if("undefined"===typeof a.error_duration)var k=0;else!isNaN(parseFloat(a.error_duration))&&isFinite(a.error_duration)?k=parseInt(a.error_duration):j="Invalid message duration. See Documentation.";var i="undefined"===typeof a.error_window_type?
"main":a.error_window_type;"main"==i?i=600:"modal"==i&&(i=400);if(isNaN(parseFloat(i))||!isFinite(i))j="Invalid message window size. See Documentation.";var o="undefined"===typeof a.error_displacement||0!=a.error_displacement?1:a.error_displacement,f="undefined"===typeof a.error_title?"":a.error_title;"undefined"!==typeof j[0]&&null!==j[0]&&(h=j);var d=b("<div class='message_error_container' style='display:block'>").html("&nbsp");b("body").append(d);a=n-i-10;0>a&&(a=0);var g=0;if("string"===typeof h||
"undefined"===typeof h[1]){"string"!==typeof h&&(h=h[0]);"string"!==typeof e&&(e=e[0]);"string"!==typeof f&&(f=f[0]);var c='                        <div class="message_error" id="message_error_0" style="position: absolute;">                            <div class="alert alert-'+e+'" style="margin-bottom: 0;">                                <a href="#" class="close">&times</a>';"undefined"!==typeof f&&(c+='                                    <h4 class="alert-heading">'+f+"</h4>                                        ");
c+="                                "+h+"                            </div>                        </div>";g++;b("body").on("click",".close",function(a){a.stopPropagation();a.preventDefault();b(this).parent().parent().parent().hide("slide",{direction:"up"},500);return false})}else c="",h.forEach(function(a){c=c+('                            <div class="message_error" id="message_error_'+g+'" style="position: absolute;">');if(typeof e==="string")c=c+('                                <div class="alert alert-'+
e+'" style="margin-bottom: 0;">                                    <a href="#" class="close">&times</a>                                            ');else if(typeof e==="object"&&typeof e[g]!=="undefined"&&e[g]!=" "&&e[g]!==null)c=c+('                                <div class="alert alert-'+e[g]+'" style="margin-bottom: 0;">                                    <a href="#" class="close">&times</a>                                            ');else{var b=parseInt(g)-1;e=e[b];c=c+('                                <div class="alert alert-'+
e+'" style="margin-bottom: 0;">                                    <a href="#" class="close">&times</a>                                            ')}if(typeof f==="string")c=c+('                                        <h4 class="alert-heading">'+f+"</h4>                                            ");else if(typeof f==="object"&&typeof f[g]!=="undefined"&&f[g]!=" "&&f[g]!==null)c=c+('                                        <h4 class="alert-heading">'+f[g]+"</h4>                                            ");
else{b=parseInt(g)-1;f=f[b];c=c+('                                        <h4 class="alert-heading">'+f+"</h4>                                            ")}c=c+("                                    "+a+"                                </div>                            </div>");g++}),b("body").on("click",".close",function(a){a.stopPropagation();a=b(this).parent().parent().attr("id");a=a.substr(a.indexOf("ror_")+4);a==g-1&&b(this).parent().parent().parent().hide("slide",{direction:"up"},500);a="message_error_"+
(parseInt(a)+1);b(this).parent().parent().hide("slide",{direction:"up"},500);b("#"+a+"").show("slide",{direction:"down"},500);a=b("#"+a+"").height();d.css("height",a);return false});d.html(c);d.hide();d.children('div[id^="message_error_"]').hide();d.css("width",i);d.children('div[id^="message_error_"]').css("width",i);d.children('div[id^="message_error_"]').css("margin-bottom","3px");1==o?(d.css({"z-index":"50",position:"absolute","margin-top":"3px"}),d.css("margin-left",a+"px")):(d.css({background:"white",
"padding-top":"3px","padding-bottom":"3px"}),d.css("padding-left",a+"px"));b(this).is("html")?(target=b(".navbar").parent().children(".container").children(".row").children(":first-child"),target.prepend(d)):b(this).prepend(d);d.show();d.children("#message_error_0").show("slide",{direction:"up"},500);h=d.children("#message_error_0").height();d.css("height",h);var l=-1;0<k&&m();var m=function(){d.children("#message_error_"+l).children().children(".close").click();l++;l<g?setTimeout(m,k):d.hide("slide",
{direction:"up"},500)}}}})(jQuery);
